/* Curated project stories. Evidence snapshots are illustrative, never live model inference. */
import Image from "next/image";
import SiteLink from './SiteLink';
import BiCDemo from './BiCDemo';
export function StudioIntro() {
    return <>
      <section className="hero" aria-labelledby="hero-title">
        <div>
          <div className="eyebrow">AI, applied ML &amp; questions worth building</div>
          <h1 id="hero-title">Big questions.<br />Small, <em>testable</em><br />worlds.</h1>
          <p className="intro"><strong>I&apos;m Luke.</strong> My current work centers on a coding system that has to survive interruption, and a small neural learner that has to prove what it learned. I want to show the hard parts: what fails, what persists, and what counts as progress.</p>
          <div className="actions"><SiteLink className="button" href="#work">Step inside the projects <span aria-hidden="true">↘</span></SiteLink><SiteLink className="text-link" href="/about/">How I work</SiteLink></div>
          <div className="portrait-row"><Image src="/images/headshot2026.webp" alt="Luke Payne" width={43} height={43}/><div><span>Software, experiments, unfinished questions.</span><span>Virginia, United States</span></div></div>
        </div>
        <div className="studio">
          <div className="studio-art">
            <span className="studio-label">THREE THREADS / ONE CURIOSITY</span>
            <svg viewBox="0 0 500 465" role="img" aria-labelledby="map-title map-desc">
              <title id="map-title">A map of three project questions</title><desc id="map-desc">Build, learn, and compare connect OpenClaw Evolutionary Coding Lab, Brain in Computer, and LLM Tool Calling Lab. This is an editorial illustration, not measured project output.</desc>
              <g fill="none" stroke="currentColor"><circle cx="250" cy="235" r="137" opacity=".25"/><circle className="orbit" cx="250" cy="235" r="173" strokeDasharray="2 19" opacity=".45"/><path d="M250 109 367 303 132 303Z" opacity=".55"/><path d="M250 109V235L367 303M250 235 132 303" strokeDasharray="4 5" opacity=".6"/><circle cx="250" cy="235" r="8" fill="#f8c27c" stroke="none"/></g>
              <g transform="translate(209 69)" fill="#f3f0e8"><rect width="26" height="26" rx="3"/><rect x="38" width="26" height="26" rx="3" opacity=".5"/><rect y="38" width="26" height="26" rx="3" opacity=".5"/><rect x="38" y="38" width="26" height="26" rx="3"/></g>
              <g transform="translate(328 260)" stroke="#f3f0e8" fill="none" strokeWidth="2"><ellipse cx="38" cy="40" rx="38" ry="14"/><ellipse cx="38" cy="40" rx="38" ry="14" transform="rotate(60 38 40)"/><ellipse cx="38" cy="40" rx="38" ry="14" transform="rotate(120 38 40)"/><circle cx="38" cy="40" r="4" fill="#f8c27c" stroke="none"/></g>
              <g transform="translate(99 274)" fill="none" stroke="#f3f0e8" strokeWidth="2"><rect width="63" height="52" rx="4"/><path d="m12 15 10 10-10 10m20 0h17"/></g>
              <g fill="currentColor" fontFamily="Consolas,monospace" fontSize="12"><text x="241" y="160" textAnchor="middle">01 / BUILD</text><text x="121" y="352" textAnchor="middle">03 / COMPARE</text><text x="366" y="352" textAnchor="middle">02 / LEARN</text></g>
            </svg>
            <div className="studio-foot"><span>TOOLS · LEARNING · EVIDENCE</span><span>↗</span></div>
          </div>
          <div className="sticker">Curiosity first.<br />Evidence follows.</div>
          <div className="art-caption"><span className="arrow" aria-hidden="true">↳</span><span>Different experiments. A shared habit:<br />make the interesting part inspectable.</span></div>
        </div>
      </section>

      </>;
}
export function FlagshipWork() {
    return <><section className="work" id="work" aria-labelledby="work-title">
        <div className="section-top"><h2 id="work-title">The work I want to show.</h2><span className="eyebrow">Three deeper stories / architecture, experiments &amp; evidence</span></div>
        <nav className="work-index" aria-label="Featured projects"><SiteLink href="#openclaw"><span>01</span>OpenClaw Evolutionary Lab</SiteLink><SiteLink href="#bic"><span>02</span>Brain in Computer</SiteLink><SiteLink href="#llm-lab"><span>03</span>LLM Tool Calling Lab</SiteLink></nav>

        <article className="flagship" id="openclaw" aria-labelledby="openclaw-title">
          <div className="flagship-head"><span className="eyebrow">01 / OpenClaw Evolutionary Coding Lab</span><span className="status-label">Active engineering / historical offline candidate</span></div>
          <div className="flagship-grid">
            <div><h3 id="openclaw-title">What happens when<br />a coding agent<br />gets interrupted?</h3><p className="lead">The interesting part starts when a task fails, a caller disappears, or a process survives its deadline.</p><p className="story">OpenClaw is my experiment in bounded coding work: explicit permissions, changes in an isolated project copy, and a result a person can inspect. Planning, task scheduling, durable records and execution components exist. Connecting them into a complete coding workflow is still the hard part.</p><div className="focus-note"><strong>My focus</strong>I’m directing the system boundaries and acceptance criteria: which actions a task may perform, what survives a restart, and what evidence is needed before a run counts as complete. Development and implementation are AI-assisted.</div><div className="project-actions"><SiteLink href="/projects/openclaw-evolutionary-lab/">Read the project &amp; eight-part series ↗</SiteLink><SiteLink href="/lab/openclaw-cancellation-and-recovery/">Follow the interruption story ↗</SiteLink></div></div>
            <figure className="artifact"><div className="artifact-top"><span>ACTUAL VALIDATION RECORD</span><span>HISTORICAL SOURCE-v10 / SEP 22</span></div><div className="receipt-number">1,612</div><div className="receipt-title">offline tests recorded for the extracted candidate</div><pre className="receipt-code">{"{\n  \"profile\": \"offline\",\n  \"testsRun\": 1612,\n  \"passed\": true,\n  \"failures\": [],\n  \"errors\": [],\n  \"nativeQualificationClaim\": \"NONE\"\n}"}</pre><div className="receipt-bound">1 expected historical failure · 17 host checks excluded</div><figcaption>Exact field excerpt from the source-v10 validation receipt. The offline wheel demo enrolled one synthetic registry candidate, with execution and other capabilities disabled. These saved results were not rerun for this preview.</figcaption></figure>
          </div>
          <div className="feature-bottom"><div><h4>What the evidence establishes</h4><p>A reproducible historical source archive and installed offline package, plus focused evidence for deadlines, stopping work and preserving outcomes. The public series explains the findings; it does not independently reproduce the local engine results.</p><div className="loop" aria-label="Intended workflow"><span>Scope a task</span><i aria-hidden="true">→</i><span>Work in a copy</span><i aria-hidden="true">→</i><span>Review a patch</span></div></div><div className="boundary"><h4>Still unfinished</h4><p>Observer and service acceptance, native startup, durable request integration, and the complete success/failure/cancellation/restart demonstration. The current convergence policy has population one; multi-population evolutionary search is not established.</p></div></div>
        </article>

        <article className="flagship bic-head" id="bic" aria-labelledby="bic-title">
          <div className="flagship-head"><span className="eyebrow">02 / Brain in Computer (BiC)</span><span className="status-label">Research prototype / public CPU inference demo</span></div>
          <div className="flagship-grid">
            <div><h3 id="bic-title">Learning a lesson<br />isn’t the same as<br />reusing its meaning.</h3><p className="lead">A small neural learner, an external local tutor, and English worlds whose answers can be checked.</p><p className="story">BiC teaches and tests temporary meanings, colors, counts and switches. The tutor proposes bounded lesson choices; the learner answers on its own during evaluation. A saved learning loop supports practice, retention checks and full-state continuation.</p><div className="focus-note"><strong>My focus</strong>I’m shaping the research questions and evidence standards: keep the tutor outside the learner’s answers, verify lesson meanings, and assess acquisition, retention and unfamiliar composition separately. AI-assisted experiments preserve failed candidates as well as promising results.</div><div className="project-actions"><SiteLink href="/projects/bic/">Read the case study ↗</SiteLink><SiteLink href="https://github.com/Dolvido/BiC/blob/main/docs/PUBLIC_DEMO.md">Run the CPU demo ↗</SiteLink><SiteLink href="https://github.com/Dolvido/BiC/blob/main/docs/SHARED_RATE_RESULTS.md">Read the controlled comparison ↗</SiteLink></div></div>
            <figure className="artifact"><div className="artifact-top"><span>RECORDED CPU DEMO</span><span>REPLAY / NOT LIVE INFERENCE</span></div><BiCDemo /><figcaption>Actual observation bytes and generated replies from the published <SiteLink href="https://github.com/Dolvido/BiC/blob/main/assets/demo-observations.json">27-turn demo record</SiteLink>. Four hand-written scenarios, not a benchmark. The 2,264,725-parameter research candidate runs without the tutor; it failed the full promotion gate.</figcaption></figure>
          </div>
          <div className="study-strip" aria-label="Bounded learning-rate comparison results"><div className="study-stat"><strong>+24.375 pp</strong><span>Lower-rate acquisition advantage<br />across 12 equally weighted cells</span></div><div className="study-stat"><strong>479 / 480</strong><span>Retention checks passed<br />one failure still blocks promotion</span></div><div className="study-stat negative"><strong>0 / 96</strong><span>Unfamiliar composition pairs<br />sequence: 1 / 96</span></div></div><p className="study-context">One inherited learning lineage; identical lesson exposure; restricted English grammar and repeatedly observed evaluation banks. Improved acquisition did not meet the complete capability and retention requirements.</p>
          <div className="feature-bottom"><div><h4>A working artifact, with a boundary</h4><p>The public release includes source, a CPU inference asset and compact evidence. The demo shows successes and errors without an LLM answering for the learner. It is distinct from the retained home learner and the older simulated-desktop labs.</p></div><div className="boundary"><h4>The open research question</h4><p>Reliable unfamiliar composition, useful tutor advantage and learned curriculum selection remain unproven. The small English worlds do not establish arbitrary language understanding, general reasoning or control of real desktop applications.</p></div></div>
        </article>

        <article className="flagship lab-feature" id="llm-lab" aria-labelledby="llm-title">
          <div className="flagship-head"><span className="eyebrow">03 / LLM Tool Calling Lab</span><span className="status-label">Released experiment / v0.1.0</span></div><div className="flagship-grid"><div><h3 id="llm-title">A useful model fit.<br />An unreliable answer.</h3><p className="story">A local chatbot can run a valid ML tool and still miss what the follow-up asks. This released test bed makes the method, data and artifacts inspectable, then scores the conversation separately from the fit.</p><div className="focus-note"><strong>My focus</strong>I define the tool interfaces and evaluation controls: keep test labels outside the conversation, separate execution from answer quality, and count failed episodes. The implementation and review process are AI-assisted.</div><div className="lab-outcome"><strong>33/48 generic · 31/48 structured</strong><br />Added planning showed no observed completion benefit.<br />Only 5/24 anomaly conversations passed.</div><p className="story">24 synthetic held-out datasets, two fixed-seed repeats per arm, one backend and unblinded AI reviews by implementation agents. No general superiority or production reliability is established.</p><div className="project-actions"><SiteLink href="/projects/llm-tool-calling-lab/">Read the case study ↗</SiteLink><SiteLink href="https://github.com/Dolvido/llm-tool-calling-lab/releases/tag/v0.1.0">Inspect source &amp; frozen evidence ↗</SiteLink></div></div><figure className="artifact"><Image loading="eager" width={1440} height={1050} className="lab-screenshot" src="/images/lab/llm-tool-calling-lab/01-question-and-evidence.png" alt="Actual LLM Tool Calling Lab interface showing a synthetic prediction question and an expandable evidence table"/><figcaption>Actual application screenshot from the existing release article. This separate post-release synthetic demonstration is excluded from the frozen benchmark. Model-generated wording in the screenshot is not a statistical significance claim.</figcaption></figure></div>
        </article>
      </section>

      </>;
}
export function SupportingWork() {
    return <><section className="supporting" aria-labelledby="supporting-title"><div className="eyebrow">Supporting work / earlier projects</div><h2 id="supporting-title">Other useful evidence.</h2><p className="supporting-intro">A few earlier projects show the API, retrieval and product work behind the current experiments.</p><article className="support-row"><div><h3>NASA CMR AI Agent</h3><span className="small-status">Independent assessment / public source</span></div><p>Natural-language Earth-science search through a Python/FastAPI application and LangGraph workflow using public NASA CMR APIs. An independent project, not an official NASA product.</p><SiteLink href="/projects/nasa-cmr-agent/">Read case study ↗</SiteLink></article><article className="support-row"><div><h3>AutoAgent</h3><span className="small-status">Experimental local application</span></div><p>Local code critiques, structured findings, SQLite feedback and retrieval of earlier examples. Model and retrieval errors remain visible; feedback does not establish better review correctness.</p><SiteLink href="/projects/autoagent/">Read case study ↗</SiteLink></article><article className="support-row"><div><h3>Fuguely</h3><span className="small-status">Private-source prototype / public case study</span></div><p>Music-teacher scheduling, student rosters, invitations, communication and billing workflows. Product-oriented full-stack work with private source.</p><SiteLink href="/projects/fuguely/">Read case study ↗</SiteLink></article></section>
      </>;
}
export function WorkingNotes() {
    return <><section className="next" id="next" aria-labelledby="next-title">
        <div><span className="plan-badge">On the drawing board · not built</span><h2 id="next-title">An alert is a starting point.<br />What comes next?</h2><p>The next Lab direction is automatic composition of different ML tools. The product hypothesis: a local telemetry workbench where metrics and an alert lead to evidence, uncertainty, and useful next checks.</p><p>Changing-condition anomaly detection comes first, with regime prediction as a transfer task. The planned 40–60-hour first milestone still needs an implementation and evaluation.</p><SiteLink className="text-link" href="/lab/llm-tool-calling-lab-first-release/">Start with what v0.1 actually tested ↗</SiteLink></div>
        <div className="flow"><div className="flow-head"><span>PROPOSED EXPERIENCE</span><span>NO LIVE RESULTS</span></div><div className="flow-box"><span>01</span>Bring metrics + an alert</div><div className="flow-arrow" aria-hidden="true">↓</div><div className="flow-box"><span>02</span>Investigate with bounded ML tools</div><div className="flow-arrow" aria-hidden="true">↓</div><div className="flow-box"><span>03</span>Inspect evidence, uncertainty &amp; next checks</div><small>v0.1 compared estimator selection.<br />Automatic model composition is future work.</small></div>
      </section>
      <section className="about" id="about" aria-labelledby="about-title"><div><div className="eyebrow">A note on how I work</div><h2 id="about-title">Curiosity needs<br />something to push against.</h2></div><div><p>I want to know what happens after the impressive first demo: when an agent is interrupted, when a learner sees a new procedure, or when a chatbot has to explain a second result.</p><p><strong>My focus is making those questions concrete.</strong> What crosses each system boundary? What evidence should a model return? What would count as success, and what would change my mind?</p><p>I use AI-assisted development to explore implementations. I want the decisions, trade-offs, and limits to be as inspectable as the code.</p></div></section>
    </>;
}
